modId: SaintGuardCircleSimplification
modName: Saint Guard Circle Simplification
modAuthor: Root50199
modAdditionalCredits: None
updateType: volatile
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
