modId: GlennBearnaZoomAndFoV
modName: Glenn Bearna Zoom
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Lag Helper
  - Zoom
  - FoV
