modId: ZoneSimplificationTaillteannTown
modName: Zone Simplification Taillteann Town
modAuthor: mabiassist and unknown
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
# recentUpdateNotes:
findiasTags:
  - Lag Helper
