modId: RemoveRaincastingCloudBlankCircle
modName: Remove Raincasting Cloud Blank Circle
modAuthor: Root50199
# modAdditionalCredits:
updateType: stable
# recentUpdateNotes:
findiasTags:
  - Combat
  - Fx
  - Lag Helper
