modId: CromBasZoomAndFoVAndDeclutterDefaultFoV
modName: Crom Bas Zoom And FoV And Declutter
modAuthor: Root50199
updateType: stable
findiasTags:
  - QoL
  - Combat
  - Visual Clarity
  - Zoom
  - FoV
  - Lag Helper
  - Crom Bas
