modId: DarkDivinerTimer
modName: Dark Diviner Timer
modAuthor: Root50199
modAdditionalCredits: Originally seen on the [Erinn World forums](https://erinn.world/forum.php?mod=viewthread&tid=23207&extra=&page=1). I found it in an unusable state, reversed it, and significantly modified it myself.
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - Visual Clarity
