modId: SacredGuardianCircleSimplification
modName: Sacred Guardian Circle Simplification
modAuthor: Root50199
# modAdditionalCredits:
updateType: stable
findiasTags:
  - Combat
  - Fx
  - Arcana
  - Visual Clarity
