modId: BriMidirEffects
modName: Bri Midir Effects
modAuthor: Root50199
updateType: stable
recentUpdateNotes: added bomb timer
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Visual Clarity
  - Bri Leith
