modId: SaintGuardCircleSimplification
modName: Saint Guard Circle Simplification
modAuthor: Root50199
modAdditionalCredits: none
updateType: stable
findiasTags:
  - Combat
  - Fx
  - Arcana
  - Visual Clarity
