modId: SaintGuardCircleSimplification
modName: Saint Guard Circle Simplification
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Fx
  - Arcana
  - Visual Clarity
