modId: BriLeithZoomAndFoV90
modName: Bri Leith Zoom And FoV90
modAuthor: Root50199
modAdditionalCredits: None
updateType: volatile
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - QoL
  - Bri Leith
  - Zoom
  - FoV
