modId: ForbiddenAlchemistFxOff
modName: Forbidden Alchemist Fx Off
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
