modId: Font
modName: Font
modAuthor: ShaggyZE, Tekashi, Matthew Welch, Unknown
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
recentUpdateNotes: none
findiasTags:
  - QoL
  - UI
