modId: ScreenshotWatermarkRemoval
modName: Screenshot Watermark Removal
modAuthor: Amaretto
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
findiasTags:
  - Cosmetic
  - QoL
