modId: PetWindowExpanded1440p
modName: Pet Window Expanded Variant 1
modAuthor: Root50199
# modAdditionalCredits:
updateType: stable
# recentUpdateNotes:
findiasTags:
  - 1440p Required
  - QoL
  - UI
