modId: GleannBearnaZoomAndFoV
modName: Gleann Bearna Zoom And Fo V
modAuthor: Root50199
modAdditionalCredits: None
updateType: volatile
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - QoL
  - Zoom
  - FoV
