modId: HideSkillDescriptionWindow
modName: Hide Skill Description Window
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - UI
  - QoL
  - Combat
