modId: GlennSimplified
modName: Glenn Simplified
modAuthor: Root50199
modAdditionalCredits: Based on a mod from the [Erinn World forums](https://erinn.world/forum.php?mod=viewthread&tid=21880).
updateType: stable
recentUpdateNotes: n/a
findiasTags: []
