modId: GlennBearnaZoomAndFoV60
modName: Glenn Bearna Zoom And 60 FoV
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - QoL
  - Zoom
  - FoV
