modId: ExpandedAuctionHouseHighRes
modName: Expanded Auction House High Res
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - UI
  - QoL
  - 1440p Required
