modId: MapsTaraShadowMissions
modName: Maps Tara Shadow Missions
modAuthor: Unknown and Rydian
modAdditionalCredits: Ported, edited and maintained by Root50199
updateType: stable
# recentUpdateNotes:
findiasTags:
  - QoL
  - UI
