modId: RemoveRaincastingCloudFilledCircle
modName: Remove Raincasting Cloud Filled Circle
modAuthor: Root50199
# modAdditionalCredits:
updateType: stable
# recentUpdateNotes:
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Visual Clarity
