modId: ElementalKnightFxOffAndHarmonicSaintChanged
modName: Elemental Knight Fx Off And Harmonic Saint Changed
modAuthor: Root50199
updateType: stable
recentUpdateNotes: Added an indicator for Pall's range
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - Visual Clarity
