modId: MelodicPuppeteerFxOff
modName: Melodic Puppeteer Fx Off
modAuthor: Root50199
# modAdditionalCredits:
updateType: stable
# recentUpdateNotes:
findiasTags:
  - Arcana
  - Combat
  - Fx
  - Lag Helper
