modId: ElementalKnightFxOffAndHarmonicSaintChangedNao
modName: Elemental Knight Fx Off And Harmonic Saint Changed Nao Pall
modAuthor: Root50199
updateType: stable
recentUpdateNotes: Added pillar type pall variant
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - Visual Clarity
