modId: TheaterDungeonSimplification
modName: Theater Dungeon Simplification
modAuthor: Synesthesia and unknown
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
recentUpdateNotes: none
findiasTags:
  - Fx
  - Lag Helper
  - Visual Clarity
