modId: BigMushrooms
modName: Big Mushrooms
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - 1440p Required
  - Arcana
  - Audio
  - Bri Leith
  - Combat
  - Crom Bas
  - Cutscene Skip
  - FoV
  - Fx
  - Glenn Bearna
  - Lag Helper
  - QoL
  - Rabbie Phantasm
  - Tech Duinn
  - UI
  - Visual Clarity
  - Zoom
