modId: BigMushrooms
modName: Big Mushrooms
modAuthor: Amaretto
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - QoL
  - Visual Clarity
