modId: BlacksmithMiniGame
modName: Blacksmith Mini Game
modAuthor: Root50199
modAdditionalCredits: Original by unknown, remade for new life by Root50199
recentUpdateNotes: Remade for Newlife
updateType: stable
findiasTags:
  - QoL
  - UI
  - Visual Clarity
