modId: ZoneSimplificationTaraTown
modName: Zone Simplification Tara Town
modAuthor: Unknown
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
# recentUpdateNotes:
findiasTags:
  - Lag Helper
