modId: CookingRuler
modName: Cooking Ruler
modAuthor: Root50199
modAdditionalCredits: Heavily modified, but originally from [this Erinn World thread](https://www.erinn.world/forum.php?mod=viewthread&tid=16795&extra=page%3D2&page=1) by 隐翅.
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - UI
  - QoL
