modId: RevivedIllusionSimplification
modName: Revived Illusion Simplification
modAuthor: Unknown
modAdditionalCredits: Cleaned up and maintained by Root50199
updateType: stable
recentUpdateNotes: none
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Tech Duinn
