modId: RevivedIllusionSimp
modName: Revived Illusion Simp
modAuthor: Root50199
modAdditionalCredits: Originally sent to me anonymously. I have changed very little beyond tidying it up.
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - QoL
  - Combat
  - Fx
  - Lag Helper
  - Tech Duinn
