modId: Status
modName: Status
modAuthor: Root50199
# modAdditionalCredits:
updateType: stable
# recentUpdateNotes:
findiasTags:
  - 1440p Required
  - Arcana
  - Audio
  - Bri Leith
  - Combat
  - Cosmetic
  - Crom Bas
  - Cutscene Skip
  - FoV
  - Fx
  - Glenn Bearna
  - Lag Helper
  - QoL
  - Rabbie Phantasm
  - Tech Duinn
  - UI
  - Visual Clarity
  - Zoom
