modId: GlennBearnaZoomAndFoV90WithDeclutter
modName: Glenn Bearna Zoom FoV 90 With Declutter
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Lag Helper
  - Zoom
  - FoV
