modId: NewModTemplate
modName: New Mod Template
modAuthor: Root50199
modAdditionalCredits: None
updateType: volatile
recentUpdateNotes: Features added/changed, important FYI etc.
findiasTags:
  - UI
  - QoL
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - Visual Clarity
  - Zoom
  - FoV
