modId: ZoneSimplificationTheaterMissions
modName: Zone Simplification Theater Missions
modAuthor: Synesthesia, unknown, and Root50199
# modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
findiasTags:
  - Fx
  - Lag Helper
  - Visual Clarity
