modId: ElementalKnightFxOffAndSaintGuardChanged
modName: Elemental Knight Fx Off And Saint Guard Changed
modAuthor: Root50199
updateType: stable
recentUpdateNotes: added an indicator for Pall's range
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - Visual Clarity
