modId: RemovePetSummonAnimations
modName: Remove Pet Summon Animations
modAuthor: Unknown, Tekashi and Root50199
# modAdditionalCredits:
updateType: stable
# recentUpdateNotes:
findiasTags:
  - Combat
  - Fx
  - QoL
