modId: MimicWhiteMesh
modName: Mimic White Mesh
modAuthor: Amaretto(Mimics), Jragon0(Strange Books)
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
recentUpdateNotes: none
findiasTags:
  - Combat
  - Fx
  - QoL
  - Visual Clarity
