modId: MimicWhiteMesh
modName: Mimic White Mesh
modAuthor: Amaretto(Mimics), Jragon0(Strange Books)
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - 1440p Required
  - Arcana
  - Audio
  - Bri Leith
  - Combat
  - Crom Bas
  - Cutscene Skip
  - FoV
  - Fx
  - Glenn Bearna
  - Lag Helper
  - QoL
  - Rabbie Phantasm
  - Tech Duinn
  - UI
  - Visual Clarity
  - Zoom
