modId: BriMap
modName: Bri Map
modAuthor: Root50199
modAdditionalCredits: None
updateType: volatile
recentUpdateNotes: removed fog from all maps and disabled zoom on the gate 1 map
findiasTags:
  - UI
  - Bri Leith
