modId: PaladinAndDarkKnightSimplification
modName: Paladin And Dark Knight Simplification
modAuthor: Unknown
# modAdditionalCredits:
updateType: stable
# recentUpdateNotes:
findiasTags:
  - Lag Helper
