modId: FontWhiteRabbit
modName: Font White Rabbit
modAuthor: Matthew Welch
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
# recentUpdateNotes:
findiasTags:
  - QoL
  - UI
