modId: DarkerGateThreeFloor
modName: Darker Gate Three Floor
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - QoL
  - Visual Clarity
  - Bri Leith
