modId: BriBronntanasEffects
modName: Bri Bronntanas Effects
modAuthor: Root50199
# modAdditionalCredits:
updateType: stable
recentUpdateNotes: added 40/20% goop removal
findiasTags:
  - Bri Leith
  - Combat
  - Fx
  - Lag Helper
  - Visual Clarity
