modId: AlternateSuccessAnimation
modName: Alternate Success Animation
modAuthor: Unknown
modAdditionalCredits: Ported and maintained by Root50199
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Audio
  - Fx
  - Cosmetic
