modId: CromBasZoomAndFoVAndDeclutter90FoV
modName: Crom Bas Zoom And FoV And Declutter 90 FoV
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - QoL
  - Combat
  - Visual Clarity
  - Zoom
  - FoV
  - Lag Helper
  - Crom Bas
