modId: AchievmentUnhideConflictTest
modName: Achievment Unhide Conflict Test
modAuthor: Root50199
updateType: volatile
recentUpdateNotes: This is a test mod to see if the achievment unhide conflict is working.
findiasTags:
  - UI
  - QoL
