modId: BriLeithZoomAndFoV
modName: Bri Leith Zoom And FoV
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - QoL
  - Bri Leith
  - Zoom
  - FoV
