modId: ElementalKnightFxOffAndSaintGuardChanged
modName: Elemental Knight Fx Off And Saint Guard Changed
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Fx
  - Lag Helper
  - Arcana
  - Visual Clarity
