modId: GlennBearnaZoomAndFoVDefaultWithDeclutter
modName: Glenn Bearna Zoom And FoV Default With Declutter
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - Combat
  - Lag Helper
  - Zoom
  - FoV
