modId: GlennBearnaZoomAndFoVDefaultWithDeclutter
modName: Glenn Bearna Zoom And FoV Default With Declutter
modAuthor: Root50199
updateType: stable
findiasTags:
  - Combat
  - Lag Helper
  - Zoom
  - FoV
