modId: PhantasmalSightSimplified
modName: Phantasmal Sight Simplified
modAuthor: Root50199
modAdditionalCredits: None
updateType: stable
recentUpdateNotes: n/a
findiasTags:
  - UI
  - QoL
  - Fx
  - Visual Clarity
